import { Roboto } from 'next/font/google';
import { Metadata } from 'next';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700']
});

export const metadata: Metadata = {
  title: {
    default: 'Next.js Tutorial - Codevolution',
    template: '%s | Codevolution'
  },
  description: 'Generated by Next.js'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt">
      <body className={roboto.className}>
        <header style={{ backgroundColor: 'lightblue', padding: '1rem' }}>
          Header
        </header>
        {children}
        <footer style={{ backgroundColor: 'ghostwhite', padding: '1rem' }}>
          Footer
        </footer>
      </body>
    </html>
  );
}
